export const technicalSkills = [
  {
    name: 'Bash',
    img: '/img/technical-skills/bash.svg',
    url: 'https://www.gnu.org/software/bash/',
  },
  { name: 'React', img: '/img/technical-skills/react.svg', url: 'https://reactjs.org/' },
  {
    name: 'Bootstrap',
    img: '/img/technical-skills/bootstrap.svg',
    url: 'https://getbootstrap.com/',
  },
  {
    name: 'CSS',
    img: '/img/technical-skills/css.svg',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  { name: 'AWS', img: '/img/technical-skills/aws.svg', url: 'https://aws.amazon.com/' },
  {
    name: 'DotNetCore',
    img: '/img/technical-skills/dotnetcore.svg',
    url: 'https://dotnet.microsoft.com/',
  },
  { name: 'Docker', img: '/img/technical-skills/docker.svg', url: 'https://www.docker.com/' },
  { name: 'GitHub', img: '/img/technical-skills/github.svg', url: 'https://github.com' },
  {
    name: 'ExpressJS',
    img: '/img/technical-skills/expressjs.svg',
    url: 'https://expressjs.com/',
  },
  {
    name: 'Firebase',
    img: '/img/technical-skills/firebase.svg',
    url: 'https://firebase.google.com/',
  },
  { name: 'Git', img: '/img/technical-skills/git.svg', url: 'https://git-scm.com/' },
  { name: 'GraphQL', img: '/img/technical-skills/graphql.svg', url: 'https://graphql.org/' },
  {
    name: 'HTML',
    img: '/img/technical-skills/html.svg',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  { name: 'Python', img: '/img/technical-skills/python.svg', url: 'https://www.python.org/' },
  { name: 'GitLab', img: '/img/technical-skills/gitlab.svg', url: 'https://gitlab.com/' },
  {
    name: 'C',
    img: '/img/technical-skills/c.svg',
    url: 'https://en.wikipedia.org/wiki/C_(programming_language)',
  },
  {
    name: 'JavaScript',
    img: '/img/technical-skills/javascript.svg',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  { name: 'MongoDB', img: '/img/technical-skills/mongodb.svg', url: 'https://www.mongodb.com/' },
  { name: 'MUI', img: '/img/technical-skills/mui.svg', url: 'https://mui.com/' },
  { name: 'Nginx', img: '/img/technical-skills/nginx.svg', url: 'https://www.nginx.com/' },
  {
    name: 'C#',
    img: '/img/technical-skills/csharp.svg',
    url: 'https://docs.microsoft.com/en-us/dotnet/csharp/',
  },
  { name: 'NestJS', img: '/img/technical-skills/nestjs.svg', url: 'https://nestjs.com/' },
  { name: 'MySQL', img: '/img/technical-skills/mysql.svg', url: 'https://www.mysql.com/' },
  {
    name: 'C++',
    img: '/img/technical-skills/cpp.svg',
    url: 'https://en.wikipedia.org/wiki/C%2B%2B',
  },
  { name: 'NodeJS', img: '/img/technical-skills/nodejs.svg', url: 'https://nodejs.org/en/' },
  { name: 'NextJS', img: '/img/technical-skills/nextjs.svg', url: 'https://nextjs.org/' },
  {
    name: 'TypeScript',
    img: '/img/technical-skills/typescript.svg',
    url: 'https://www.typescriptlang.org/',
  },
  {
    name: 'PostgreSQL',
    img: '/img/technical-skills/postgresql.svg',
    url: 'https://www.postgresql.org/',
  },
  { name: 'Redux', img: '/img/technical-skills/redux.svg', url: 'https://redux.js.org/' },
  { name: 'Java', img: '/img/technical-skills/java.svg', url: 'https://www.java.com/en/' },
  {
    name: 'TailwindCSS',
    img: '/img/technical-skills/tailwindcss.svg',
    url: 'https://tailwindcss.com/',
  },
  {
    name: 'Algolia',
    img: '/img/technical-skills/algolia.svg',
    url: 'https://www.algolia.com/',
  },
  { name: 'Ubuntu', img: '/img/technical-skills/ubuntu.svg', url: 'https://ubuntu.com/' },
  {
    name: 'VSCode',
    img: '/img/technical-skills/vscode.svg',
    url: 'https://code.visualstudio.com/',
  },
  {
    name: 'ElasticSearch',
    img: '/img/technical-skills/elasticsearch.svg',
    url: 'https://www.elastic.co/',
  },
  {
    name: 'CircleCI',
    img: '/img/technical-skills/circleci.svg',
    url: 'https://circleci.com/',
  },
  {
    name: 'Flutter',
    img: '/img/technical-skills/flutter.svg',
    url: 'https://flutter.dev/',
  },
  {
    name: 'Jenkins',
    img: '/img/technical-skills/jenkins.svg',
    url: 'https://www.jenkins.io/',
  },
];
